services:
  - type: web
    name: cognitive-care-backend
    runtime: python
    plan: free

    rootDir: backend

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app

    healthCheckPath: /api/health

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10

      - key: MONGO_URI
        sync: false

      - key: DATABASE_NAME
        sync: false

      - key: JWT_SECRET
        sync: false